travis:
  secure:
    BINSTAR_TOKEN: xZ+lL2qgYsNiptVi1x5vwDozM9iqU4124vBAXmwFT5agOxOsqFjsfKld9vrlzb5PX8ZIeyAPVBMzgS/zrK7q++0ZHPeLZIManrngEBB3p1mdKk4UDxHeRloBE56wNWpcj8XOnH55mi3klmzRazGVQy9CHAoJBstgi321/ASCzu+su1YbFD0FR6dgFpFCgdOZSxNd94fYavGUIYhZgMQWneInjPtk3XgMxtYRKDNOcDF4btKQpQ2lkW9RY8pywlJCKYf3eHLKYwVkh7A9O0F827XiULn5YHB7tD5iz8QN9AWgrqMrSRWXcZYVZB4jdzKq44G/LY6ueCxp9SSoaDda96pUGsfS1C85CCilXBA3/FSVLKE4184POoxcJcv+ZsX0WKB+Z33SaF+vTYSelF7xkkKkTqpWxmXaltyme3556RMbEMAVC+9wfgPAmJuKUe9TkzsgrgPuk4WNn/OxFjqIXYKK4rN3VDiU3lkgXQs2/Ap8TLNWqJoLLT24H9jq8pqXRKP2eyUQ92nBqs1oiFo0fy3nAeWqs4JUL0P6mnab9Pt4XpIeeg7UFG7PS9VvcK578uK/KjCLXY0NMYIQgNFOVMqW3Wwp0ywNEA+4zLGbgd6u6Y8DYQJmZ9fjWxx9TX6hd4UB37PEs5scXmO3JW6o4u5ZiTXQTTPh0OxRPxLp4bY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
